#!/usr/bin/env bash
# generate-env.sh — derive the runtime env files from the user's config.yaml.
#
#   usage: generate-env.sh [config.yaml]
#
# Reads (first that exists): $1, $WT_CONFIG_FILE, ~/.config/wt/config.yaml.
# A missing config is fine: the defaults below apply. Writes:
#   $WT_CONFIG_DIR/env.sh          (bash, sourced by lib/wt/config.sh)
#   $WT_CONFIG_DIR/dashboard.env   (KEY=VALUE, systemd EnvironmentFile=)
set -eu

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=parse-yaml.sh
. "$SCRIPT_DIR/parse-yaml.sh"

WT_CONFIG_DIR="${WT_CONFIG_DIR:-$HOME/.config/wt}"
CONFIG_FILE="${1:-${WT_CONFIG_FILE:-$WT_CONFIG_DIR/config.yaml}}"

expand_home() { case "$1" in "~"|"~/"*) printf '%s%s' "$HOME" "${1#\~}";; *) printf '%s' "$1";; esac; }

# ---- defaults ---------------------------------------------------------------
DEFAULT_BASE_BRANCH=main
REVIEW_OWNER=""
REVIEW_MODEL=sonnet
AGENT_DEFAULT=claude
MODEL_CHOICES=""
DASHBOARD_PORT=7300
DEPLOY_URL_REGEX=""
SSH_HOST=""
ATTENTION_NEEDS_RE=""
ATTENTION_DONE_RE=""
IDE_BACKEND=none
IDE_PORT_BASE=6000
SECRETS_SRC=""
SESSIONS_DIR="$HOME/.wt-sessions"
HOOKS_DIR="$HOME/.config/wt/hooks"
STACKS=""
FORWARD_PORTS=""
declare -A REPOS=()
declare -A CLONE_PATHS=()

# ---- read the config --------------------------------------------------------
if [ -f "$CONFIG_FILE" ]; then
  while IFS=$'\t' read -r key val; do
    case "$key" in
      repos.*)                REPOS["${key#repos.}"]="$val" ;;
      clone_paths.*)          CLONE_PATHS["${key#clone_paths.}"]="$(expand_home "$val")" ;;
      default_base_branch)    DEFAULT_BASE_BRANCH="$val" ;;
      github.review_owner)    REVIEW_OWNER="$val" ;;
      github.review_model)    REVIEW_MODEL="$val" ;;
      agents.default)         AGENT_DEFAULT="$val" ;;
      agents.model_choices.*) MODEL_CHOICES="${MODEL_CHOICES:+$MODEL_CHOICES }$val" ;;
      dashboard.port)         DASHBOARD_PORT="$val" ;;
      dashboard.deploy_url_regex) DEPLOY_URL_REGEX="$val" ;;
      dashboard.ssh_host)     SSH_HOST="$val" ;;
      dashboard.attention.needs_re) ATTENTION_NEEDS_RE="$val" ;;
      dashboard.attention.done_re)  ATTENTION_DONE_RE="$val" ;;
      ide.backend)            IDE_BACKEND="$val" ;;
      ide.port_base)          IDE_PORT_BASE="$val" ;;
      secrets.source)         SECRETS_SRC="$(expand_home "$val")" ;;
      sessions.meta_dir)      SESSIONS_DIR="$(expand_home "$val")" ;;
      hooks.dir)              HOOKS_DIR="$(expand_home "$val")" ;;
      stacks.*)               STACKS="${STACKS:+$STACKS }$val" ;;
      ports.*)                FORWARD_PORTS="${FORWARD_PORTS:+$FORWARD_PORTS }$val" ;;
    esac
  done < <(wt_yaml_flatten "$CONFIG_FILE")
fi

# ---- write env.sh (bash) ----------------------------------------------------
mkdir -p "$WT_CONFIG_DIR"
ENV_SH="$WT_CONFIG_DIR/env.sh"
{
  echo "# Generated by lib/config/generate-env.sh from ${CONFIG_FILE} — do not edit."
  echo "# Regenerate after editing the config: lib/config/generate-env.sh"
  printf 'export WT_DEFAULT_BASE_BRANCH=%q\n' "$DEFAULT_BASE_BRANCH"
  printf 'export WT_REVIEW_OWNER=%q\n'        "$REVIEW_OWNER"
  printf 'export WT_REVIEW_MODEL=%q\n'        "$REVIEW_MODEL"
  printf 'export WT_AGENT_DEFAULT=%q\n'       "$AGENT_DEFAULT"
  printf 'export WT_MODEL_CHOICES=%q\n'       "$MODEL_CHOICES"
  printf 'export WT_DASHBOARD_PORT=%q\n'      "$DASHBOARD_PORT"
  printf 'export WT_DEPLOY_URL_REGEX=%q\n'    "$DEPLOY_URL_REGEX"
  printf 'export WT_SSH_HOST=%q\n'            "$SSH_HOST"
  printf 'export WT_IDE_BACKEND=%q\n'         "$IDE_BACKEND"
  printf 'export WT_IDE_PORT_BASE=%q\n'       "$IDE_PORT_BASE"
  printf 'export WT_SECRETS_SRC=%q\n'         "$SECRETS_SRC"
  printf 'export WT_SESSIONS_DIR=%q\n'        "$SESSIONS_DIR"
  printf 'export WT_HOOKS_DIR=%q\n'           "$HOOKS_DIR"
  printf 'export WT_STACKS=%q\n'              "$STACKS"
  printf 'export WT_FORWARD_PORTS=%q\n'       "$FORWARD_PORTS"
  echo 'declare -gA WT_REPOS=()'
  for k in "${!REPOS[@]}"; do printf 'WT_REPOS[%q]=%q\n' "$k" "${REPOS[$k]}"; done
  echo 'declare -gA WT_PATHS=()'
  for k in "${!CLONE_PATHS[@]}"; do printf 'WT_PATHS[%q]=%q\n' "$k" "${CLONE_PATHS[$k]}"; done
} > "$ENV_SH.tmp"
mv "$ENV_SH.tmp" "$ENV_SH"

# ---- write dashboard.env (systemd EnvironmentFile) --------------------------
# systemd env files take no quoting/escaping games; values are used verbatim.
json_escape() { printf '%s' "$1" | sed -e 's/\\/\\\\/g' -e 's/"/\\"/g'; }
CLONE_PATHS_JSON="{"
first=1
for k in "${!CLONE_PATHS[@]}"; do
  [ $first = 1 ] || CLONE_PATHS_JSON="$CLONE_PATHS_JSON,"
  CLONE_PATHS_JSON="$CLONE_PATHS_JSON\"$(json_escape "$k")\":\"$(json_escape "${CLONE_PATHS[$k]}")\""
  first=0
done
CLONE_PATHS_JSON="$CLONE_PATHS_JSON}"
MODEL_CHOICES_CSV="${MODEL_CHOICES// /,}"

DASH_ENV="$WT_CONFIG_DIR/dashboard.env"
{
  echo "# Generated by lib/config/generate-env.sh from ${CONFIG_FILE} — do not edit."
  echo "PORT=$DASHBOARD_PORT"
  echo "WT_SESSIONS_DIR=$SESSIONS_DIR"
  echo "WT_CLONE_PATHS=$CLONE_PATHS_JSON"
  echo "WT_MODEL_CHOICES=$MODEL_CHOICES_CSV"
  echo "WT_SSH_HOST=$SSH_HOST"
  echo "WT_AGENT_DEFAULT=$AGENT_DEFAULT"
  echo "# PR-review watcher (auto-starts a review session for PRs assigned to you)."
  echo "# Runs only when PR_REVIEW_OWNER is non-empty AND PR_REVIEW_WATCH is not 0."
  echo "# PR_REVIEW_DRYRUN=1 logs what it would do without creating sessions."
  echo "PR_REVIEW_WATCH=1"
  echo "PR_REVIEW_OWNER=$REVIEW_OWNER"
  echo "PR_REVIEW_MODEL=$REVIEW_MODEL"
  echo "DEPLOY_RE=$DEPLOY_URL_REGEX"
  echo "# Attention-classifier overrides (config dashboard.attention.*); empty = built-in English defaults."
  echo "NEEDS_RE=$ATTENTION_NEEDS_RE"
  echo "DONE_RE=$ATTENTION_DONE_RE"
  echo "# Attention digest: cheap LLM triage of idle sessions. On-demand by default"
  echo "# (dashboard button); set DIGEST_POLL_MS>0 for a timer. DIGEST=0 disables."
  echo "DIGEST=1"
  echo "DIGEST_MODEL=haiku"
  echo "DIGEST_POLL_MS=0"
} > "$DASH_ENV.tmp"
mv "$DASH_ENV.tmp" "$DASH_ENV"

echo "wrote $ENV_SH"
echo "wrote $DASH_ENV"
