#!/usr/bin/env bash
# generate-env.sh — derive the runtime env files from the user's config.yaml.
#
#   usage: generate-env.sh [config.yaml]
#
# Reads (first that exists): $1, $WT_CONFIG_FILE, ~/.config/wt/config.yaml.
# A missing config is fine: the defaults below apply. Writes:
#   $WT_CONFIG_DIR/env.sh          (bash, sourced by lib/wt/config.sh)
#   $WT_CONFIG_DIR/dashboard.env   (KEY=VALUE, systemd EnvironmentFile=)
set -eu

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=parse-yaml.sh
. "$SCRIPT_DIR/parse-yaml.sh"

WT_CONFIG_DIR="${WT_CONFIG_DIR:-$HOME/.config/wt}"
CONFIG_FILE="${1:-${WT_CONFIG_FILE:-$WT_CONFIG_DIR/config.yaml}}"

expand_home() { case "$1" in "~"|"~/"*) printf '%s%s' "$HOME" "${1#\~}";; *) printf '%s' "$1";; esac; }

# ---- defaults ---------------------------------------------------------------
DEFAULT_BASE_BRANCH=main
REVIEW_OWNER=""
REVIEW_MODEL=sonnet
AGENT_DEFAULT=claude
MODEL_CHOICES=""
DASHBOARD_PORT=7300
DEPLOY_URL_REGEX=""
SSH_HOST=""
IDE_BACKEND=none
IDE_PORT_BASE=6000
IDE_RIDER_VERSION=2026.1.3
SECRETS_SRC=""
SESSIONS_DIR="$HOME/.wt-sessions"
HOOKS_DIR="$HOME/.config/wt/hooks"
STACKS=""
DOTNET_VERSION=""
PLAYWRIGHT_BROWSERS=""
PLAYWRIGHT_VERSION=""
FORWARD_PORTS=""
declare -A REPOS=()
declare -A CLONE_PATHS=()

# ---- read the config --------------------------------------------------------
if [ -f "$CONFIG_FILE" ]; then
  while IFS=$'\t' read -r key val; do
    case "$key" in
      repos.*)                REPOS["${key#repos.}"]="$val" ;;
      clone_paths.*)          CLONE_PATHS["${key#clone_paths.}"]="$(expand_home "$val")" ;;
      default_base_branch)    DEFAULT_BASE_BRANCH="$val" ;;
      github.review_owner)    REVIEW_OWNER="$val" ;;
      github.review_model)    REVIEW_MODEL="$val" ;;
      agents.default)         AGENT_DEFAULT="$val" ;;
      agents.model_choices.[0-9]*) MODEL_CHOICES="${MODEL_CHOICES:+$MODEL_CHOICES }$val" ;;
      dashboard.port)         DASHBOARD_PORT="$val" ;;
      dashboard.deploy_url_regex) DEPLOY_URL_REGEX="$val" ;;
      dashboard.ssh_host)     SSH_HOST="$val" ;;
      ide.backend)            IDE_BACKEND="$val" ;;
      ide.port_base)          IDE_PORT_BASE="$val" ;;
      ide.rider_version)      IDE_RIDER_VERSION="$val" ;;
      secrets.source)         SECRETS_SRC="$(expand_home "$val")" ;;
      sessions.meta_dir)      SESSIONS_DIR="$(expand_home "$val")" ;;
      hooks.dir)              HOOKS_DIR="$(expand_home "$val")" ;;
      stacks.[0-9]*)          STACKS="${STACKS:+$STACKS }$val" ;;
      stack_options.dotnet_version) DOTNET_VERSION="$val" ;;
      stack_options.playwright_browsers.[0-9]*) PLAYWRIGHT_BROWSERS="${PLAYWRIGHT_BROWSERS:+$PLAYWRIGHT_BROWSERS }$val" ;;
      stack_options.playwright_version) PLAYWRIGHT_VERSION="$val" ;;
      ports.[0-9]*)           FORWARD_PORTS="${FORWARD_PORTS:+$FORWARD_PORTS }$val" ;;
    esac
  done < <(wt_yaml_flatten "$CONFIG_FILE")
fi

# ---- write env.sh (bash) ----------------------------------------------------
mkdir -p "$WT_CONFIG_DIR"
ENV_SH="$WT_CONFIG_DIR/env.sh"
{
  echo "# Generated by lib/config/generate-env.sh from ${CONFIG_FILE} — do not edit."
  echo "# Regenerate after editing the config: lib/config/generate-env.sh"
  printf 'export WT_DEFAULT_BASE_BRANCH=%q\n' "$DEFAULT_BASE_BRANCH"
  printf 'export WT_REVIEW_OWNER=%q\n'        "$REVIEW_OWNER"
  printf 'export WT_REVIEW_MODEL=%q\n'        "$REVIEW_MODEL"
  printf 'export WT_AGENT_DEFAULT=%q\n'       "$AGENT_DEFAULT"
  printf 'export WT_MODEL_CHOICES=%q\n'       "$MODEL_CHOICES"
  printf 'export WT_DASHBOARD_PORT=%q\n'      "$DASHBOARD_PORT"
  printf 'export WT_DEPLOY_URL_REGEX=%q\n'    "$DEPLOY_URL_REGEX"
  printf 'export WT_SSH_HOST=%q\n'            "$SSH_HOST"
  printf 'export WT_IDE_BACKEND=%q\n'         "$IDE_BACKEND"
  printf 'export WT_IDE_PORT_BASE=%q\n'       "$IDE_PORT_BASE"
  printf 'export WT_IDE_RIDER_VERSION=%q\n'   "$IDE_RIDER_VERSION"
  printf 'export WT_SECRETS_SRC=%q\n'         "$SECRETS_SRC"
  printf 'export WT_SESSIONS_DIR=%q\n'        "$SESSIONS_DIR"
  printf 'export WT_HOOKS_DIR=%q\n'           "$HOOKS_DIR"
  printf 'export WT_STACKS=%q\n'              "$STACKS"
  # _DEFAULT on purpose: exporting WT_DOTNET_VERSION itself would clobber a
  # user-provided env override when install.sh sources this file.
  printf 'export WT_DOTNET_VERSION_DEFAULT=%q\n' "$DOTNET_VERSION"
  printf 'export WT_PLAYWRIGHT_BROWSERS=%q\n'    "$PLAYWRIGHT_BROWSERS"
  printf 'export WT_PLAYWRIGHT_VERSION_DEFAULT=%q\n' "$PLAYWRIGHT_VERSION"
  printf 'export WT_FORWARD_PORTS=%q\n'       "$FORWARD_PORTS"
  echo 'declare -gA WT_REPOS=()'
  for k in "${!REPOS[@]}"; do printf 'WT_REPOS[%q]=%q\n' "$k" "${REPOS[$k]}"; done
  echo 'declare -gA WT_PATHS=()'
  for k in "${!CLONE_PATHS[@]}"; do printf 'WT_PATHS[%q]=%q\n' "$k" "${CLONE_PATHS[$k]}"; done
} > "$ENV_SH.tmp"
mv "$ENV_SH.tmp" "$ENV_SH"

# ---- write dashboard.env (systemd EnvironmentFile) --------------------------
# systemd env files take no quoting/escaping games; values are used verbatim.
json_escape() { printf '%s' "$1" | sed -e 's/\\/\\\\/g' -e 's/"/\\"/g'; }
CLONE_PATHS_JSON="{"
first=1
for k in "${!CLONE_PATHS[@]}"; do
  [ $first = 1 ] || CLONE_PATHS_JSON="$CLONE_PATHS_JSON,"
  CLONE_PATHS_JSON="$CLONE_PATHS_JSON\"$(json_escape "$k")\":\"$(json_escape "${CLONE_PATHS[$k]}")\""
  first=0
done
CLONE_PATHS_JSON="$CLONE_PATHS_JSON}"
MODEL_CHOICES_CSV="${MODEL_CHOICES// /,}"

# systemd's EnvironmentFile treats a backslash in an UNQUOTED value as an
# escape character (\? becomes ?, \s becomes s), which silently destroyed
# regex values (invalid regex -> the dashboard crashed on startup). Every
# value is therefore emitted quoted. Semantics verified against systemd 255:
# inside double quotes, doubling backslashes and escaping inner double quotes
# round-trips exactly (single quotes preserve backslashes too, but cannot
# contain a single quote at all — no shell-style '\'' concatenation).
env_quote() { local v="$1"; v="${v//\\/\\\\}"; v="${v//\"/\\\"}"; printf '"%s"' "$v"; }
env_line()  { printf '%s=%s\n' "$1" "$(env_quote "$2")"; }

DASH_ENV="$WT_CONFIG_DIR/dashboard.env"
{
  echo "# Generated by lib/config/generate-env.sh from ${CONFIG_FILE} — do not edit."
  env_line PORT             "$DASHBOARD_PORT"
  env_line WT_SESSIONS_DIR  "$SESSIONS_DIR"
  env_line WT_CLONE_PATHS   "$CLONE_PATHS_JSON"
  env_line WT_MODEL_CHOICES "$MODEL_CHOICES_CSV"
  env_line WT_SSH_HOST      "$SSH_HOST"
  env_line WT_AGENT_DEFAULT "$AGENT_DEFAULT"
  echo "# PR-review watcher (auto-starts a review session for PRs assigned to you)."
  echo "# Runs only when PR_REVIEW_OWNER is non-empty AND PR_REVIEW_WATCH is not 0."
  echo "# PR_REVIEW_DRYRUN=1 logs what it would do without creating sessions."
  env_line PR_REVIEW_WATCH  "1"
  env_line PR_REVIEW_OWNER  "$REVIEW_OWNER"
  env_line PR_REVIEW_MODEL  "$REVIEW_MODEL"
  env_line DEPLOY_RE        "$DEPLOY_URL_REGEX"
  echo "# Attention digest: cheap LLM triage of idle sessions. On-demand by default"
  echo "# (dashboard button); set DIGEST_POLL_MS>0 for a timer. DIGEST=0 disables."
  env_line DIGEST           "1"
  env_line DIGEST_MODEL     "haiku"
  env_line DIGEST_POLL_MS   "0"
} > "$DASH_ENV.tmp"
mv "$DASH_ENV.tmp" "$DASH_ENV"

echo "wrote $ENV_SH"
echo "wrote $DASH_ENV"
